version: 0.2

phases:

  build:
    commands:
      - echo "Packaging the application..."
      - mvn clean package -DskipTests
      - echo "Preparing Elastic Beanstalk bundle..."

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - target/trial.jar
  discard-paths: yes
